swagger: '2.0'
info:
  version: 1.0.0
  title: Csds calls to retrieve domains
  description: get your domains here
host: adminlogin.liveperson.net
basePath: /api/account/
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /{accountId}/service/baseURI.json:
    get:
      parameters:
        - name: accountId
          description: account id
          type: string
        - name: version
          in: query
          description: api version
          required: true
          type: String
          default: "1.0"
      responses:
        200:
          description:  List all domains
          schema:
            title: domains
            type: array
            items:
              $ref: '#/definitions/Csds'
definitions:
 Csds:
    type: object
    properties:
      service:
        type: string
      account:
        type: string
      baseURI:
        type: string
    
